In [5]:
import json 
import datetime

import numpy as np 
import pandas as pd
import plotly.express as px
twitterData = pd.read_csv("data.csv", sep=',(?=\S)', engine='python')
twitterData.head()

<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:7: SyntaxWarning: invalid escape sequence '\S'
C:\Users\shivh\AppData\Local\Temp\ipykernel_11448\3829858637.py:7: SyntaxWarning: invalid escape sequence '\S'
  twitterData = pd.read_csv("data.csv", sep=',(?=\S)', engine='python')

,id,screenName,tags,avatar,followersCount,friendsCount,lang,lastSeen,tweetId,friends
0,"""1969527638""","""LlngoMakeEmCum_""","[ ""#nationaldogday"" ]","""http://pbs.twimg.com/profile_images/534286217...",319,112,"""en""",1472271687519,"""769310701580083200""","[ ""1969574754"", ""1969295556"", ""1969284056"", ""1..."
1,"""51878493""","""_notmichelle""","[ ""#nationaldogday"" ]","""http://pbs.twimg.com/profile_images/761977602...",275,115,"""en""",1472270622663,"""769309490038439936""","[ ""60789485"", ""2420931980"", ""2899776756"", ""127..."
2,"""1393409100""","""jesseayye""","[ ""#narcos"" ]","""http://pbs.twimg.com/profile_images/713282938...",120,107,"""en""",1472804144409,"""771622623583186944""","[ ""86868062"", ""19697415"", ""2998836604"", ""45629..."
3,"""232891415""","""MrBrianLloyd""","[ ""#gloryoutnow"" ]","""http://pbs.twimg.com/profile_images/133440668...",492,325,"""en""",1472269186776,"""769308131696467969""","[ ""361335082"", ""1405248468"", ""24626354"", ""7256..."
4,"""710130422907207680""","""sarahdorat_16""","[ ""#nationaldogday"" ]","""http://pbs.twimg.com/profile_images/767180520...",128,218,"""en""",1472271397356,"""769309769144283137""","[ ""1571896093"", ""768938323612008448"", ""2548665..."

In [6]:
def delete_quotes(x):
    return x[1:-1]
for column in ["id", "screenName", "avatar", "lang", "tweetId"]:
    twitterData[column] = twitterData[column].apply(delete_quotes)
    
for column in ["tags", "friends"]:
    twitterData[column] = twitterData[column].apply(lambda x: json.loads(x))
twitterData.head()

,id,screenName,tags,avatar,followersCount,friendsCount,lang,lastSeen,tweetId,friends
0,1969527638,LlngoMakeEmCum_,[#nationaldogday],http://pbs.twimg.com/profile_images/5342862178...,319,112,en,1472271687519,769310701580083200,"[1969574754, 1969295556, 1969284056, 196961221..."
1,51878493,_notmichelle,[#nationaldogday],http://pbs.twimg.com/profile_images/7619776021...,275,115,en,1472270622663,769309490038439936,"[60789485, 2420931980, 2899776756, 127410795, ..."
2,1393409100,jesseayye,[#narcos],http://pbs.twimg.com/profile_images/7132829382...,120,107,en,1472804144409,771622623583186944,"[86868062, 19697415, 2998836604, 456295047, 74..."
3,232891415,MrBrianLloyd,[#gloryoutnow],http://pbs.twimg.com/profile_images/1334406683...,492,325,en,1472269186776,769308131696467969,"[361335082, 1405248468, 24626354, 725675895965..."
4,710130422907207680,sarahdorat_16,[#nationaldogday],http://pbs.twimg.com/profile_images/7671805202...,128,218,en,1472271397356,769309769144283137,"[1571896093, 768938323612008448, 2548665930, 3..."

In [7]:
twitterData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              40000 non-null  object
 1   screenName      40000 non-null  object
 2   tags            40000 non-null  object
 3   avatar          40000 non-null  object
 4   followersCount  40000 non-null  int64
 5   friendsCount    40000 non-null  int64
 6   lang            40000 non-null  object
 7   lastSeen        40000 non-null  int64
 8   tweetId         40000 non-null  object
 9   friends         40000 non-null  object
dtypes: int64(3), object(7)
memory usage: 3.1+ MB

In [8]:
twitterData.describe()

       followersCount   friendsCount      lastSeen
count    4.000000e+04   40000.000000  4.000000e+04
mean     3.692349e+03     919.101450  1.472287e+12
std      9.136179e+04    3417.849318  1.010296e+08
min      1.010000e+02     101.000000  1.472249e+12
25%      2.420000e+02     253.000000  1.472259e+12
50%      4.400000e+02     423.000000  1.472265e+12
75%      9.240000e+02     801.000000  1.472270e+12
max      1.476555e+07  238749.000000  1.472808e+12

In [9]:
twitterData['lang'].value_counts()

lang
en    40000
Name: count, dtype: int64

In [10]:
twitterData.drop(["lang", 'avatar', 'tweetId'], axis=1)

,id,screenName,tags,followersCount,friendsCount,lastSeen,friends
0,1969527638,LlngoMakeEmCum_,[#nationaldogday],319,112,1472271687519,"[1969574754, 1969295556, 1969284056, 196961221..."
1,51878493,_notmichelle,[#nationaldogday],275,115,1472270622663,"[60789485, 2420931980, 2899776756, 127410795, ..."
2,1393409100,jesseayye,[#narcos],120,107,1472804144409,"[86868062, 19697415, 2998836604, 456295047, 74..."
3,232891415,MrBrianLloyd,[#gloryoutnow],492,325,1472269186776,"[361335082, 1405248468, 24626354, 725675895965..."
4,710130422907207680,sarahdorat_16,[#nationaldogday],128,218,1472271397356,"[1571896093, 768938323612008448, 2548665930, 3..."
...,...,...,...,...,...,...,...
39995,2392502478,bieberdestine,"[#respecttylerjoseph, #nationaldogday]",13645,13624,1472289186728,"[4430903653, 408582743, 968989339, 76875785456..."
39996,1014398065,Yeh_its_Choolwe,[#belgiangp],119,113,1472288980846,"[29359583, 24515927, 345358431, 73986447294112..."
39997,177430436,cachelebell,[#nationaldogday],2023,1882,1472288982066,"[323073788, 4855395791, 803659230, 2345804690,..."
39998,20240488,LifestyleMGroup,[#weekend],2881,1526,1472288984948,"[86101271, 7111412, 8830542, 349236669, 800592..."
39999,946109466,jessmorris98,[#respecttylerjoseph],1679,1592,1472289145743,"[759526036992208897, 726502847009923072, 75049..."

In [11]:
fig = px.histogram(twitterData, x="followersCount", nbins=10000)
fig.show()

In [12]:
fig = px.histogram(twitterData[(twitterData['followersCount'] > 1000) & (twitterData['followersCount'] < 100000)], x="followersCount", nbins=1000)
fig.show()

In [13]:
fig = px.histogram(twitterData, x="friendsCount", nbins=1000)
fig.show()

In [15]:
rank = 100
followersCount = -1

followersRank = []
followersCounts = []

while True:
    followersCount = twitterData[(twitterData["followersCount"] >= rank) & (twitterData["followersCount"] < rank * 10)].shape[0]
    if followersCount == 0:
        break
        
    followersRank.append(rank)
    followersCounts.append(followersCount)
    rank *= 10

followersCountByRankDict = {
    "count": followersCounts,
    "rank": followersRank
}
followersCountByRank = pd.DataFrame(data=followersCountByRankDict)

fig = px.scatter(followersCountByRank, x="rank", y="count")
fig.show()

In [16]:
rank = 100
friendsCount = -1

friendRank = []
friendsCounts = []

while True:
    friendsCount = twitterData[(twitterData["friendsCount"] >= rank) & (twitterData["friendsCount"] < rank * 10)].shape[0]
    #print(friendsCount)
    if friendsCount == 0:
        break
        
    friendRank.append(rank)
    friendsCounts.append(friendsCount)
    rank *= 10

friendsCountByRankDict = {
    "count": friendsCounts,
    "rank": friendRank
}
#print(friendsCountByRankDict)
friendsCountByRank = pd.DataFrame(data=friendsCountByRankDict)

fig = px.scatter(friendsCountByRank, x="rank", y="count")
fig.show()

In [17]:
fig = px.scatter(twitterData, x="followersCount", y="friendsCount", hover_data=["screenName"])
fig.show()

In [18]:
def parse_date(x):
    return datetime.datetime.fromtimestamp(x/1000.0) \
            .strftime("%Y-%m-%d")


twitterData['lastSeenDatetime'] = twitterData['lastSeen'].apply(parse_date)
twitterData['lastSeenDatetime'].value_counts()

lastSeenDatetime
2016-08-27    37660
2016-09-01      963
2016-09-02      691
2016-08-29      472
2016-08-28      214
Name: count, dtype: int64

In [19]:
fig = px.histogram(twitterData, x="lastSeenDatetime", nbins=100)
fig.show()

In [20]:
fig = px.scatter(twitterData, x="lastSeenDatetime", y="followersCount")
fig.show()

In [21]:
fig = px.scatter(twitterData, x="lastSeenDatetime", y="friendsCount")
fig.show()